#!/usr/bin/env python3
"""E04-S06 - generates the combiner decoder's test vectors.

The vectors come from the **decompilation's headers** - the `G_CC_*`,
`G_CCMUX_*` and `G_ACMUX_*` macros - and not from a transcription by hand. A
transcription goes wrong silently and then lets a wrong decoder pass: the test
and the code would share the same error.

    tools/win95/gen_combiner_vectors.py [decomp-root] > vectors.inc

The default root is the neighbouring native port. This repository does not have
those sources: it works from recompiled MIPS, which is precisely why the E04-S06
inventory cannot be re-verified here by the same method.
"""
import re, sys, pathlib

root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "/var/www/Diddy-Kong-Racing")

def read_defines(pattern):
    out = {}
    for header in root.glob("include/**/*.h"):
        try:
            text = header.read_text(errors="ignore")
        except OSError:
            continue
        for m in re.finditer(pattern, text, re.M):
            out.setdefault(m.group(1), int(m.group(2)))
    return out

ccmux = read_defines(r'^#define\s+G_CCMUX_(\w+)\s+(\d+)')
acmux = read_defines(r'^#define\s+G_ACMUX_(\w+)\s+(\d+)')
if not ccmux or not acmux:
    sys.exit(f"error: G_CCMUX/G_ACMUX not found under {root}")

combiners = {}
for header in root.glob("include/**/*.h"):
    try:
        text = header.read_text(errors="ignore")
    except OSError:
        continue
    for m in re.finditer(r'^#define\s+G_CC_(\w+)\s+(.+)$', text, re.M):
        args = [a.strip() for a in m.group(2).split(',')]
        if len(args) == 8:
            combiners[m.group(1)] = args

def shiftl(v, s, w):
    return (v & ((1 << w) - 1)) << s

def pack(args):
    """The four GCCc*w* macros from gbi.h, applied as they are.

    **The field widths are not uniform, and that changes the value.**
    `G_CCMUX_0` is 31, which fits in the five bits of field `c` but not in the
    four bits of `a` and `b`: the hardware stores 15 there. A decoder therefore
    cannot return 31 for those positions, and expecting it would be demanding
    the impossible.

    A first version of this generator emitted the raw value, and the test
    accused the decoder - which was right. The expected values are therefore
    truncated here as the hardware truncates them.

    Consequence to remember for E05-S03: **the same symbolic `0` does not encode
    the same way depending on position**, and a mapping table written on names
    rather than on values would go wrong.
    """
    a, b, c, d, Aa, Ab, Ac, Ad = args
    A, B, C, D = ccmux[a] & 0xF, ccmux[b] & 0xF, ccmux[c] & 0x1F, ccmux[d] & 0x7
    AA, AB = acmux[Aa] & 0x7, acmux[Ab] & 0x7
    AC, AD = acmux[Ac] & 0x7, acmux[Ad] & 0x7
    # gsDPSetCombineMode(x, x): the same set for both cycles.
    w0 = (shiftl(A, 20, 4) | shiftl(C, 15, 5) | shiftl(AA, 12, 3) | shiftl(AC, 9, 3)
          | shiftl(A, 5, 4) | shiftl(C, 0, 5))
    w1 = (shiftl(B, 28, 4) | shiftl(B, 24, 4) | shiftl(AA, 21, 3) | shiftl(AC, 18, 3)
          | shiftl(D, 15, 3) | shiftl(AB, 12, 3) | shiftl(AD, 9, 3)
          | shiftl(D, 6, 3) | shiftl(AB, 3, 3) | shiftl(AD, 0, 3))
    return w0, w1, (A, B, C, D, AA, AB, AC, AD)

print("/* Generated by tools/win95/gen_combiner_vectors.py - do not edit. */")
print(f"/* Source: {root}/include - {len(combiners)} G_CC_* macros. */")
print("typedef struct {")
print("    const char *name;")
print("    unsigned int w0, w1;")
print("    unsigned char a, b, c, d, Aa, Ab, Ac, Ad;")
print("} combiner_vector;")
print()
print("static const combiner_vector COMBINER_VECTORS[] = {")
for name in sorted(combiners):
    try:
        w0, w1, f = pack(combiners[name])
    except KeyError as e:
        print(f"    /* {name}: unknown input {e} - skipped */")
        continue
    print(f'    {{ "G_CC_{name}", 0x{w0:08X}u, 0x{w1:08X}u, '
          f'{f[0]}, {f[1]}, {f[2]}, {f[3]}, {f[4]}, {f[5]}, {f[6]}, {f[7]} }},')
print("};")
