#!/usr/bin/env python3
"""E01-S05 - builds the stubs the oracle harness needs.

    LC_ALL=C <failing link> 2>&1 | tools/win95/oracle/generate-stubs.py > stubs.c

`LC_ALL=C` is not decoration. GNU ld translates its diagnostics, and this machine
runs a French system: without it the linker phrases the undefined reference in
another language and this script recognises nothing. Rather than carry one
pattern per language - a list that is wrong the day someone links under a third
locale - it matches the untranslated form only, and **stops loudly** if it read a
non-empty input without finding a single symbol. That is the same reasoning as
the stubs themselves: better a stop than a silent empty result.

The harness runs the game's functions **in isolation**, without the rest of the
runtime. The linker must therefore be satisfied for everything the recompiled
code calls and nobody supplies here: `librecomp`'s helpers, the project's hooks,
the N64 system functions.

The input is the **linker's error output**, and not a symbol dump. It is the
linker that is authoritative: it has already consulted libc, libm and libgcc,
and what it declares undefined really is. Starting from `nm` would mean guessing
which libraries supply what - and the first version of this script, which did,
stubbed out `lrintf` and `__fprintf_chk`.

The stubs are **generated** and not written by hand, for two reasons. The first
is that they then follow the code's regeneration: a function that appears is not
forgotten. The second is that a hand-written stub ends up containing an
implementation, and the day it is wrong, nobody looks there.

Each one **aborts** instead of returning a value. That is the property that
counts: if a function under comparison reached a stub, the digest would compare
emptiness twice and the comparison would be hollow without saying so. A loud stop
beats an agreement obtained by accident.
"""
import re
import sys


# GNU ld, untranslated. See the note on LC_ALL at the top of this file.
RX_UNDEFINED = re.compile(r"undefined reference to [`\u2018']([^'\u2019]+)")


def main(argv):
    del argv
    missing = set()
    read_anything = False
    for line in sys.stdin:
        if line.strip():
            read_anything = True
        for m in RX_UNDEFINED.finditer(line):
            missing.add(m.group(1).strip())
    missing = sorted(missing)

    if read_anything and not missing:
        print("generate-stubs.py: read a non-empty input without finding a "
              "single undefined reference.\n"
              "Re-run the link under LC_ALL=C: a translated linker says the "
              "same thing in words this script does not read.", file=sys.stderr)
        return 1

    print("/* Generated by tools/win95/oracle/generate-stubs.py - do not edit. */")
    print("#include <stdio.h>")
    print("#include <stdlib.h>")
    print("#include <stdint.h>")
    print()
    print("static void stub_reached(const char *name)")
    print("{")
    print("    /* A stub reached would make the comparison hollow: two targets")
    print("       would agree on emptiness. We stop rather than keep quiet. */")
    print('    fprintf(stderr, "\\nINVALID HARNESS: call to %s\\n", name);')
    print("    abort();")
    print("}")
    print()
    for name in missing:
        print(f'void {name}(void) {{ stub_reached("{name}"); }}')
    print(f"\n/* {len(missing)} stub(s). */", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
