#!/usr/bin/env python3
"""Generate the N64Recomp TOML configuration for DKR from the recomp policy.

Linux port of the TOML-generation stage of scripts/Prepare-DKR-Runtime.ps1.
The output must be byte-identical to what the PowerShell path produces for the
same inputs; scripts/compare_recomp_toml.py checks that.

Entry point resolution follows the same rule as the Windows script: prefer the
`mainproc` symbol, which DKR's decomp documents as the function run once IPL3
has completed, over the raw ROM header PC. The header PC may point at bootstrap
code that is not represented as an ELF function, and N64Recomp can only select
a real function symbol.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import shutil
import subprocess
import sys

SYMBOL_LINE = re.compile(r"^\s*([0-9A-Fa-f]+)\s+([A-Za-z])\s+(\S+)\s*$")
MDEBUG_SECTION = re.compile(r"^.*\s\.mdebug\s", re.MULTILINE)


def fail(message: str) -> "NoReturn":  # type: ignore[name-defined]
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(1)


def run_tool(tool: str, args: list[str]) -> str:
    resolved = shutil.which(tool)
    if resolved is None:
        fail(f"{tool} is not on PATH. Install the MIPS binutils first.")
    result = subprocess.run(
        [resolved, *args], check=False, text=True,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )
    if result.returncode != 0:
        fail(f"{tool} failed:\n{result.stdout}")
    return result.stdout


def rom_header_entrypoint(rom_path: pathlib.Path) -> int:
    with rom_path.open("rb") as handle:
        header = handle.read(12)
    if len(header) < 12:
        fail(f"ROM is too short to contain a header: {rom_path}")
    return int.from_bytes(header[8:12], "big")


def resolve_entrypoint(elf_path: pathlib.Path, header_pc: int) -> tuple[int, str, bool]:
    symbols = run_tool("mips-linux-gnu-nm", ["-n", "--defined-only", str(elf_path)])
    sections = run_tool("mips-linux-gnu-readelf", ["-S", "-W", str(elf_path)])

    mainproc_address: int | None = None
    header_symbol: tuple[int, str] | None = None

    for line in symbols.splitlines():
        match = SYMBOL_LINE.match(line)
        if match is None:
            continue
        address = int(match.group(1), 16)
        symbol_type = match.group(2)
        name = match.group(3)
        if name == "mainproc":
            mainproc_address = address
        if address == header_pc and symbol_type in "TtWw":
            header_symbol = (address, name)

    if mainproc_address is not None:
        selected_address, selected_symbol = mainproc_address, "mainproc"
    elif header_symbol is not None:
        selected_address, selected_symbol = header_symbol
    else:
        fail(
            "The DKR ELF contains neither the mainproc symbol nor a text symbol "
            f"at the ROM header entry point 0x{header_pc:08X}."
        )

    if selected_address & 3:
        fail(
            f"Resolved entry point {selected_symbol} at 0x{selected_address:08X}, "
            "but it is not word-aligned."
        )

    return selected_address, selected_symbol, bool(MDEBUG_SECTION.search(sections))


def quote(value: str) -> str:
    return '"' + str(value).replace('"', '\\"') + '"'


def build_toml(policy: dict, elf: str, rom: str, output: str,
               entrypoint: int, use_mdebug: bool) -> str:
    def names(key: str) -> str:
        return ", ".join(quote(entry["name"]) for entry in policy.get(key, []))

    function_sizes = ", ".join(
        f'{{ name = "{entry["name"]}", size = {entry["size"]} }}'
        for entry in policy.get("functionSizes", [])
    )
    manual_funcs = ", ".join(
        f'{{ name = "{entry["name"]}", section = "{entry["section"]}", '
        f'vram = {entry["vram"]}, size = {entry["size"]} }}'
        for entry in policy.get("manualFunctions", [])
    )
    instruction_patches = "\n\n".join(
        f'[[patches.instruction]]\nfunc = "{entry["function"]}"\n'
        f'vram = {entry["vram"]}\nvalue = {entry["value"]}'
        for entry in policy.get("instructionPatches", [])
    )
    function_hooks = "\n\n".join(
        '[[patches.hook]]\nfunc = "{func}"\nbefore_vram = {vram}\ntext = "{text}"'.format(
            func=entry["function"],
            vram=entry["beforeVram"],
            text=str(entry["text"]).replace("\\", "\\\\").replace('"', '\\"'),
        )
        for entry in policy.get("functionHooks", [])
    )

    return f"""# Generated by Prepare-DKR-Runtime.ps1.
# This is the first-pass DKR CPU recompilation configuration. DKR-specific
# stubs, manual boundaries and instruction patches will be added from the
# emitted diagnostics.
[input]
entrypoint = 0x{entrypoint:08X}
use_mdebug = {str(use_mdebug).lower()}
elf_path = "{elf}"
rom_file_path = "{rom}"
output_func_path = "{output}"
manual_funcs = [{manual_funcs}]
function_sizes = [{function_sizes}]

[patches]
stubs = [{names("stubs")}]
renamed = [{names("renamed")}]
ignored = [{names("ignored")}]

# BEGIN DKR_INSTRUCTION_PATCHES
{instruction_patches}
# END DKR_INSTRUCTION_PATCHES

# BEGIN DKR_FUNCTION_HOOKS
{function_hooks}
# END DKR_FUNCTION_HOOKS
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--elf", required=True, type=pathlib.Path,
                        help="Matching DKR ELF built from the decomp")
    parser.add_argument("--rom", required=True, type=pathlib.Path,
                        help="ROM built alongside that ELF")
    parser.add_argument("--policy", required=True, type=pathlib.Path,
                        help="dkr.us.v77.recomp-policy.json")
    parser.add_argument("--output-funcs", required=True, type=pathlib.Path,
                        help="Directory N64Recomp writes generated functions to")
    parser.add_argument("--output", required=True, type=pathlib.Path,
                        help="TOML file to write")
    args = parser.parse_args()

    for path in (args.elf, args.rom, args.policy):
        if not path.is_file():
            fail(f"missing input: {path}")

    policy = json.loads(args.policy.read_text(encoding="utf-8"))
    if policy.get("schemaVersion") != 1:
        fail("Unsupported DKR recompilation policy schema.")

    header_pc = rom_header_entrypoint(args.rom)
    entrypoint, symbol, use_mdebug = resolve_entrypoint(args.elf, header_pc)
    print(f"ROM header entry point: 0x{header_pc:08X}")
    print(f"Resolved entry point:   {symbol} at 0x{entrypoint:08X}")
    print(f"use_mdebug:             {str(use_mdebug).lower()}")

    args.output_funcs.mkdir(parents=True, exist_ok=True)
    toml = build_toml(
        policy,
        elf=args.elf.resolve().as_posix(),
        rom=args.rom.resolve().as_posix(),
        output=args.output_funcs.resolve().as_posix(),
        entrypoint=entrypoint,
        use_mdebug=use_mdebug,
    )
    # BOM-free on purpose: not every TOML parser accepts a BOM before the first key.
    args.output.write_text(toml, encoding="utf-8", newline="\n")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
