#!/usr/bin/env bash
# E09-S01 - sets up the emulated test environment: 86Box, BIOS set, a Pentium II /
# Voodoo 2 machine matching the target, and a host<->guest transfer disk.
#
# Installs nothing system-wide: everything goes into a user prefix. The Windows 95
# installation medium is NOT downloaded: it is proprietary Microsoft software, which
# the user must supply.
set -euo pipefail

PREFIX="${DKR_WIN95_PREFIX:-$HOME/.local/dkr-win95}"
VM_NAME="${DKR_WIN95_VM:-dkr-p2-voodoo2}"
VM="$PREFIX/vm/$VM_NAME"
BOX_VERSION="v6.0"
BOX_BUILD="b9001"

# The target settled by ADR 0002 (E00-S05). Changeable in order to try the
# fallbacks.
#
# WARNING: the three Voodoo settings below are written into 86box.cfg, but 86Box
# did NOT apply them when this machine was first set up - it kept the text as it
# was while emulating a Voodoo 1 with 2 MB + 2 MB. Observed on screen: the settings
# dialog showed a plain 3dfx Voodoo Graphics board while the file said type = 1,
# and Glide answered "expected Voodoo, none detected".
#
# So the model must be CHECKED once, through the dialog:
#
#   86Box -S   ->   Display -> Voodoo Graphics board -> Configure
#
# (the labels appear in the interface's own language) and "3Dfx Voodoo 2" chosen
# there, with 4 MB of frame buffer and 4 MB of texture memory. After that passage,
# the same values in the file are honoured.
CPU_FAMILY="${DKR_WIN95_CPU_FAMILY:-pentium2_deschutes}"
CPU_SPEED="${DKR_WIN95_CPU_SPEED:-400000000}"
MEM_KB="${DKR_WIN95_MEM_KB:-65536}"          # 64 MB
VOODOO_TYPE="${DKR_WIN95_VOODOO_TYPE:-1}"    # 0 = Voodoo Graphics, 1 = Voodoo 2
VOODOO_FB_MB="${DKR_WIN95_VOODOO_FB:-4}"
VOODOO_TEX_MB="${DKR_WIN95_VOODOO_TEX:-4}"

say() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || die "$1 is required but absent"; }
need curl
need tar
need python3

mkdir -p "$PREFIX/bin" "$PREFIX/opt" "$VM"

# --- 86Box -------------------------------------------------------------------
if [[ ! -x "$PREFIX/opt/86box/squashfs-root/AppRun" ]]; then
  say "Fetching 86Box $BOX_VERSION"
  mkdir -p "$PREFIX/opt/86box"
  curl -fsSL -o "$PREFIX/opt/86box/86Box.AppImage" \
    "https://github.com/86Box/86Box/releases/download/$BOX_VERSION/86Box-Linux-x86_64-$BOX_BUILD.AppImage"
  chmod +x "$PREFIX/opt/86box/86Box.AppImage"
  # Extraction rather than mounting: FUSE is often absent from build machines.
  ( cd "$PREFIX/opt/86box" && ./86Box.AppImage --appimage-extract >/dev/null )
else
  say "86Box already present"
fi

# --- BIOS set ----------------------------------------------------------------
if [[ ! -d "$PREFIX/opt/86box/roms/machines" ]]; then
  say "Fetching the 86Box BIOS set"
  mkdir -p "$PREFIX/opt/86box/roms"
  tmp="$(mktemp -d)"
  curl -fsSL -o "$tmp/roms.tar.gz" https://github.com/86Box/roms/archive/refs/heads/master.tar.gz
  tar xzf "$tmp/roms.tar.gz" -C "$tmp"
  cp -r "$tmp/roms-master/." "$PREFIX/opt/86box/roms/"
  rm -rf "$tmp"
else
  say "BIOS set already present"
fi
[[ -d "$PREFIX/opt/86box/roms/machines/p2bls" ]] \
  || die "The BIOS set does not contain the p2bls motherboard (Asus P2B-LS, 440BX)"

# --- mtools, to write into the transfer disk without root --------------------
if [[ ! -x "$PREFIX/bin/mcopy" ]]; then
  say "Local installation of mtools"
  tmp="$(mktemp -d)"
  ( cd "$tmp" && apt-get download mtools >/dev/null 2>&1 ) \
    || die "apt-get download mtools failed; install mtools some other way"
  dpkg-deb -x "$tmp"/mtools_*.deb "$PREFIX/opt/mtools"
  for t in mcopy mformat mmd mdir mdel mtype; do
    ln -sf "$PREFIX/opt/mtools/usr/bin/$t" "$PREFIX/bin/$t"
  done
  rm -rf "$tmp"
fi

# --- disk images -------------------------------------------------------------
# Created, partitioned and formatted by scripts/prepare_win95_install.py, which
# needs the user's ISO in order to fill the source disk.
#
# A DOS hard disk requires a partition table: a raw FAT volume, without an MBR, is
# simply not seen by DOS. That is why the images are not created here.
if [[ ! -f "$VM/install.img" ]]; then
  say "Disk images not prepared - next step:"
  echo "    scripts/prepare_win95_install.py --iso /path/to/W95.iso"
fi

# --- machine configuration ---------------------------------------------------
say "Writing $VM/86box.cfg"
cat > "$VM/86box.cfg" <<EOF
# Test machine for the DKR-R port to Windows 95 + 3dfx.
# Generated by scripts/Setup-Win95-TestVM.sh - see docs/TEST-ENVIRONMENT.md.
# The target settled by ADR 0002 (E00-S05).

[General]
vid_renderer = qt_software
vid_resize = 0
window_remember = 0
confirm_exit = 0
confirm_save = 0

[Machine]
machine = p2bls
cpu_family = $CPU_FAMILY
cpu_speed = $CPU_SPEED
cpu_multi = 4.0
cpu_use_dynarec = 1
fpu_type = internal
mem_size = $MEM_KB
time_sync = local

[Video]
gfxcard = virge375_pci
voodoo = 1

[3dfx Voodoo Graphics #1]
type = $VOODOO_TYPE
framebuffer_memory = $VOODOO_FB_MB
texture_memory = $VOODOO_TEX_MB
bilinear = 1
dithersub = 0
render_threads = 2
sli = 0

[Input devices]
mouse_type = ps2
joystick_type = 2axis_2button

[Sound]
sndcard = sb16
sound_type = float
opl_type = ymfm

[Storage controllers]
hdc = internal
fdc = internal

[Hard disks]
hdd_01_parameters = 63, 16, 2080, 0, ide
hdd_01_fn = win95.img
hdd_01_ide_channel = 0:0
hdd_02_parameters = 63, 16, 1024, 0, ide
hdd_02_fn = transfer.img
hdd_02_ide_channel = 0:1
hdd_03_parameters = 63, 16, 261, 0, ide
hdd_03_fn = install.img
hdd_03_ide_channel = 1:1

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_01_fn = freedos-boot.img
cdrom_01_parameters = 8, ide
cdrom_01_ide_channel = 1:0
cdrom_01_image_path =

[Network]
net_01_card = none
EOF

cat <<EOF

$(say "Environment ready")

  86Box       : $PREFIX/opt/86box/squashfs-root/AppRun
  BIOS        : $PREFIX/opt/86box/roms
  Machine     : $VM
  Disk C:     : $VM/win95.img    (system, to be installed)
  Disk D:     : $VM/transfer.img (host <-> guest transfer)
  Disk E:     : $VM/install.img   (Windows 95 source)
  Floppy      : $VM/freedos-boot.img (FreeDOS boot)

Next step - it needs YOUR Windows 95 medium, which is proprietary Microsoft
software and is not downloaded by these scripts:

  scripts/prepare_win95_install.py --iso /path/to/W95.iso
  scripts/Run-Win95-VM.sh

Then, at the FreeDOS prompt: FDISK, reboot, FORMAT C: /U, and
E:\WIN95\INSTALL.EXE. Next the 3dfx drivers, then --snapshot.

See docs/TEST-ENVIRONMENT.md.
EOF
